spring:
  servlet:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB
  datasource:
    platform: postgres
    password: ${PROD_DB_PASSWORD}
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true