spring:
  servlet:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB
  datasource:
    platform: postgres
    password: admin
    url: jdbc:postgresql://localhost:5433/police
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    show-sql: true