spring:
  servlet:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB
  datasource:
    platform: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true